### ISSUE TITLE
cannot migrate undo

### ISSUE THREAD

**Issue by huoshiqiu** [abelosorio/sequelize_replace_enum_postgres#8]
```
'use strict';
const replaceEnum = require('sequelize-replace-enum-postgres').default;

module.exports = {
  up: (queryInterface, Sequelize) => {
    return replaceEnum({
      queryInterface,
      tableName: 'Orders',
      columnName: 'source',
      newValues: [ 'wangpiao', 'taobao' ],
      enumName: 'enum_Orders_source',
    });
  },

  down: (queryInterface, Sequelize) => {
    return replaceEnum({
      queryInterface,
      tableName: 'Orders',
      columnName: 'source',
      newValues: [ 'wangpiao' ],
      enumName: 'enum_Orders_source',
    });
  },
};
```

had this error when undo

```
 SequelizeDatabaseError: invalid input value for enum "enum_Orders_source_new": "taobao"
```

**Comment by abelosorio** [comment]
Hi @huoshiqiu thanks for reporting this.

I'll check it and let you know as soon as I found the issue.

**Comment by CEOehis** [comment]
Hello @huoshiqiu I think I ran into the same issue as you did. I finally found out what the problem was.

It seems when you ran `db:migration:undo` on your database, there was at least an entry in your `Orders` table that had the value `taobao` in the `source` column.

The way this package works, it creates a new enum type with the new values, deletes the old enum type and then renames the new enum type to the old enum type name. 

However when the database tries to use the current enum type (i.e the one without values `taobao`) it notices some entries on the table that still have a `source` column value of `taobao` and throws an error:"invalid input type", since the current enum type does not support it.

What I think you can do is modify the `down` method to first delete or update entries with the no longer needed enum type value in the source column, before then running the `replaceEnum` script. 

Of course this is only viable in your development environment since you would not want to tamper with production data.

I hope this helped. Let me know if you need me to clarify. 

cc @abelosorio

**Comment by abelosorio** [comment]
Hi @CEOehis, thanks for your contribution.

...and actually you're right. Before removing a value from an ENUM you should update your table and change those values.

I'll close this issue according to @CEOehis's comment: https://github.com/abelosorio/sequelize_replace_enum_postgres/issues/8#issuecomment-421747605.

@huoshiqiu let me know if you need any further help with this.

Best!
